name: CI - Smoke
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run Smoke
        run: mvn -B -q clean test -Psmoke -DsuiteFile="testng.xml"
#      - name: Upload Allure Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results-smoke
#          path: target/allure-results
