name: Nightly - Regression
on:
  schedule:
    - cron: '30 18 * * *'  # ~ 00:00 IST
  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run Regression
        run: mvn -B clean test -Pregression -Dheadless=true -Dbrowser=chrome
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression
          path: target/allure-results
